modules:
  - ./docs/docs-client
  - ./docs/docs-site
  - ./kinetica-browser
  - ./kinetica-compiler
  - ./kinetica-data
  - ./kinetica-forms
  - ./kinetica-markdown
  - ./kinetica-motion
  - ./kinetica-persist
  - ./kinetica-router
  - ./kinetica-runtime
  - ./kinetica-test
  - ./kinetica-theme
  - ./samples/annotated
  - ./samples/browser-bench
  - ./samples/browser-counter
  - ./samples/browser-tests
  - ./samples/browser-todo
  - ./samples/server-components
  - ./samples/server-components-client
  - ./samples/server-components-shared
  - ./samples/todo
